version: "3.6"
services:
  # MongoDb
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379"